# Model arguments
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: ccvl/OpenImages_3DSR_apr23_sampled24k_NT_llava_24k
dataset_test_split: val
dataset_configs:
- all 
data_dir: ./data/openimages/train/
llava_dir: ./data/llava_datasets/LLaVA-Tuning/
num_processes: 4

# SFT trainer config
dataset_text_field: ""
dataset_kwargs:
  skip_prepare_dataset: true
remove_unused_columns: false
bf16: true
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-06
lr_scheduler_type: cosine
warmup_ratio: 0.1
log_level: info
logging_steps: 1
logging_strategy: steps
log_completions: true
max_length: 2048
min_pixels: 59716
max_pixels: 200704
max_steps: -1
num_train_epochs: 100
output_dir: data/Qwen2.5-VL-7B-SFT
overwrite_output_dir: true
per_device_train_batch_size: 6
push_to_hub: false
report_to:
- wandb
save_strategy: steps
save_steps: 1000
seed: 42