# Model arguments
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: ccvl/SpatialReasonerTrain-RL
dataset_test_split: val
dataset_configs:
- all
data_dir: ./data/openimages/
# Num processes is less by 1 as vLLM is using 1 GPU
num_processes: 3

# GRPO trainer config
reward_funcs: ['accuracy', 'format']
beta: 0.0
bf16: true
use_vllm: true
vllm_device: auto
vllm_gpu_memory_utilization: 0.6
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-07
lr_scheduler_type: cosine
warmup_ratio: 0.1
log_level: info
logging_steps: 1
logging_strategy: steps
log_completions: true
max_prompt_length: 2048
max_completion_length: 512
min_pixels: 59716
max_pixels: 200704
max_steps: -1
num_generations: 4
num_train_epochs: 100
output_dir: data/Qwen2.5-VL-7B-GRPO
overwrite_output_dir: true
per_device_train_batch_size: 12
push_to_hub: false
report_to:
- wandb
save_strategy: steps
save_steps: 1000
seed: 42
